"""add user registration idempotency

Revision ID: bed7baddfe96
Revises: 62c782c21708
Create Date: 2026-09-01 21:52:26.193932

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bed7baddfe96'
down_revision: str | None = '62c782c21708'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idempotency_key', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('idempotency_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_users_idempotency_key'), 'users', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_idempotency_key'), table_name='users')
    op.drop_column('users', 'idempotency_hash')
    op.drop_column('users', 'idempotency_key')
    # ### end Alembic commands ###
